---
otr_root_dir: "/opt/otr"
otr_user: "otr"

version: "1.0.12"
arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'x64' }}"
otr_artifact_url: "https://github.com/darkplusplus/opentakrouter/releases/download/v{{ version }}/opentakrouter-v{{ version }}-linux-{{ arch }}.tar.gz"

node_name: inventory_hostname

###
config:
  AllowedHosts: "*"
  server:
    data: "{{ otr_root_dir}}"
    name: "{{ node_name | default(inventory_hostname) }}"
    api:
      port: 8080
      swagger: true
      ssl: false
      cert: server.p12
      passphrase: atakatak
    websockets:
      enabled: true
      port: 5000
      ssl: false
      cert: server.p12
      passphrase: atakatak
    tak:
      tcp:
        enabled: true
        port: 8087
      tls:
        enabled: false
        port: 8089
        cert: server.p12
        passphrase: atakatak
    
